export const dashboardCopy: Record<'th' | 'zh' | 'en', Record<string, string>> = {
  th: {
    'dash.credits': 'เครดิตคงเหลือ',
    'dash.creditReset': 'รีเซ็ตทุกสิ้นเดือน',
    'dash.nav.home': 'หน้าหลัก',
    'dash.nav.create': 'สร้างเนื้อหา',
    'dash.nav.library': 'คลังผลงาน',
    'dash.nav.history': 'ประวัติ',
    'dash.nav.settings': 'ตั้งค่า',
    'dash.upgrade.title': 'อัปเกรดเป็น Pro',
    'dash.upgrade.desc': 'ปลดล็อคฟีเจอร์โซเชียลมีเดียและโปสเตอร์รีวิว',
    'dash.upgrade.btn': 'อัปเกรด ฿249/เดือน',
    'dash.upgrade.btn2': 'อัปเกรด',
    'dash.logout': 'ออกจากระบบ',
    'dash.welcome.label': 'ยินดีต้อนรับกลับมา',
    'dash.welcome.prefix': 'สวัสดี,',
    'dash.creditsLeft': 'เครดิตคงเหลือ',
    'dash.creditOverview': 'สรุปเครดิตเดือนนี้',
    'dash.cr': 'cr',
    'dash.resetDate': 'รีเซ็ต 1 พ.ค. 2026',
    'dash.feat.copy': 'AI คัดลอก',
    'dash.feat.enhance': 'ปรับปรุงภาพ',
    'dash.feat.social': 'โซเชียลมีเดีย',
    'dash.feat.collage': 'คอลลาจ',
    'dash.free': 'ฟรี',
    'dash.perUse': 'cr/ครั้ง',
    'dash.quickActions': 'เริ่มสร้างเลย',
    'dash.action.generate': 'สร้างภาพ AI',
    'dash.action.generate.desc': 'อัปโหลดและปรับปรุงภาพอาหาร',
    'dash.action.copy': 'AI เขียนคำโฆษณา',
    'dash.action.copy.desc': 'สร้างคำอธิบายเมนูอัตโนมัติ',
    'dash.action.layout': 'จัดเลย์เอาต์เมนู',
    'dash.action.layout.desc': 'สร้างเมนูรูปแบบสวยงาม',
    'dash.action.social': 'ส่งออกโซเชียลมีเดีย',
    'dash.action.social.desc': 'Facebook, Instagram, LINE OA',
    'dash.action.poster': 'โปสเตอร์รีวิว',
    'dash.action.poster.desc': 'สร้างโปสเตอร์จากรีวิวลูกค้า',
    'dash.action.festival': 'แม่แบบเทศกาลไทย',
    'dash.action.festival.desc': 'สงกรานต์ ตรุษจีน ลอยกระทง',
    'dash.recentActivity': 'กิจกรรมล่าสุด',
    'dash.noActivity': 'ยังไม่มีกิจกรรม เริ่มสร้างเนื้อหาเลย!',
    'dash.create.title': 'สร้างเนื้อหา',
    'dash.create.desc': 'เลือกฟีเจอร์จากหน้าหลักเพื่อเริ่มสร้าง',
    'dash.create.back': 'กลับหน้าหลัก',
    'dash.history.title': 'ประวัติการใช้งาน',
    'dash.settings.title': 'ตั้งค่าบัญชี',
    'dash.settings.identity.title': 'ข้อมูลร้านอาหาร',
    'dash.settings.identity.namePlaceholder': 'ชื่อของคุณ',
    'dash.settings.identity.restaurantPlaceholder': 'ชื่อร้านอาหาร',
    'dash.settings.security.title': 'ความปลอดภัยของบัญชี',
    'dash.settings.security.emailHint': 'ไม่สามารถเปลี่ยนที่อยู่อีเมลได้โดยตรง โปรดติดต่อฝ่ายสนับสนุนหากจำเป็น',
    'dash.settings.preferences.title': 'การตั้งค่า',
    'dash.settings.plan.activeStatus': 'สถานะการใช้งาน',
    'dash.settings.saveBar.title': 'การเปลี่ยนแปลงที่ยังไม่ได้บันทึก',
    'dash.settings.saveBar.desc': 'ปรับปรุงข้อมูลเพื่อดำเนินการต่อ',
    'dash.settings.saveBar.discard': 'ละทิ้ง',
    'dash.settings.saveBar.save': 'บันทึกการเปลี่ยนแปลง',
    'dash.settings.saveBar.saving': 'กำลังบันทึก...',
    'dash.settings.success': 'อัปเดตโปรไฟล์สำเร็จ',
    'dash.settings.error': 'อัปเดตโปรไฟล์ไม่สำเร็จ',
    'dash.settings.name': 'ชื่อร้าน',
    'dash.settings.restaurant': 'ชื่อร้านอาหาร',
    'dash.settings.email': 'อีเมล',
    'dash.settings.lang': 'ภาษา',
    'dash.settings.save': 'บันทึก',
    'dash.settings.plan': 'แผนปัจจุบัน',
    'dash.settings.free': 'ฟรีตลอดไป',
    'dash.toast.used': 'ใช้เครดิต',
    'dash.toast.remain': 'คงเหลือ:',
    'dash.create.heroTitle': 'ออกแบบคอนเทนต์ถัดไปของร้าน',
    'dash.create.heroDesc': 'เลือกเวิร์กโฟลว์ที่ต้องการ แล้วเข้าสู่ Studio หรือศูนย์จัดการที่เหมาะกับงานนั้นทันที',
    'dash.route.referral': 'แนะนำเพื่อน',
    'dash.route.channel': 'ช่องทางและส่วนแบ่ง',
    'dash.home.heroTitle': 'ยกระดับภาพเมนูและการเติบโตของร้านในที่เดียว',
    'dash.home.heroDesc': 'เปิด Studio เพื่อสร้างภาพใหม่ จากนั้นไหลต่อไปยังคลังผลงาน ประวัติ และศูนย์โปรโมตโดยไม่หลุดจากพื้นที่ทำงานเดียวกัน',
    'dash.home.primaryCta': 'เข้า Studio',
    'dash.home.secondaryCta': 'เปิดคลังผลงาน',
    'dash.home.referralTitle': 'ศูนย์เติบโตและการแนะนำ',
    'dash.home.referralDesc': 'ติดตามลิงก์ชวนเพื่อน การแปลงผล ค่าคอมมิชชั่นที่รอดำเนินการ และยอดที่พร้อมแลกในมุมมองเดียว',
    'dash.home.channelTitle': 'ศูนย์ช่องทางและการแบ่งรายได้',
    'dash.home.channelDesc': 'ดูการผูกช่องทาง ค่าคอมมิชชั่น การหักคืน และรอบการปิดยอดในพื้นที่เดียว',
    'dash.home.activityViewAll': 'ดูทั้งหมด',
    'dash.home.studioTitle': 'Studio',
    'dash.home.libraryTitle': 'คลังผลงาน',
    'dash.home.libraryDesc': 'จัดการภาพต้นฉบับ ผลลัพธ์ที่สร้าง และงานที่เผยแพร่ในพื้นที่กว้างที่อ่านง่ายกว่าเดิม',
    'dash.home.settingsDesc': 'ดูแลข้อมูลร้าน ภาษา และแพ็กเกจบัญชี โดยไม่ต้องหลุดจากประสบการณ์ Dashboard',
    'dash.create.workflow.studioTitle': 'AI Studio',
    'dash.create.workflow.studioDesc': 'สร้าง ปรับแต่ง และเลือกภาพอาหารเวอร์ชันสมบูรณ์ในพื้นที่ทำงานเฉพาะทาง',
    'dash.create.workflow.libraryTitle': 'Asset Library',
    'dash.create.workflow.libraryDesc': 'รีวิวภาพที่อัปโหลด ผลลัพธ์ที่สร้าง และสินทรัพย์ที่เผยแพร่ในตัวจัดการที่กว้างและชัดเจนกว่าเดิม',
    'dash.create.workflow.historyTitle': 'History Center',
    'dash.create.workflow.historyDesc': 'เข้าไปดูบิล งานสร้างย้อนหลัง และบันทึกการใช้งานผ่านเส้นทางที่แชร์ลิงก์ได้จริง',
    'dash.create.stepLabel': 'ขั้นตอน',
    'dash.create.flowTitle': 'Production Flow',
    'dash.create.flowDesc': 'Dashboard ใหม่ควรเป็นตัวจัดเส้นทางและการจัดการ ส่วน Studio เป็นแกนกลางของงานสร้างจริง',
    'dash.create.adaptiveTitle': 'Adaptive Workspace',
    'dash.create.adaptiveDesc': 'หน้า Library, History และ Referral ไม่ควรถูกบีบอยู่ในคอนเทนเนอร์แคบแบบเดิมอีกต่อไป',
    'dash.channel.loadError': 'โหลดข้อมูลช่องทางไม่สำเร็จ',
    'dash.channel.kicker': 'Channel Revenue Share',
    'dash.channel.heroTitle': 'ควบคุมคู่ค้า ค่าคอมมิชชั่น และรอบปิดยอดจากพื้นที่เดียว',
    'dash.channel.heroDesc': 'มุมมองนี้รวมการผูกช่องทาง รายการค่าคอมมิชชั่น รายการหักคืน และการปิดยอด เพื่อให้ทีมธุรกิจอ่านสถานะได้เร็วโดยไม่ต้องเข้าใจโมเดลบัญชีของแพลตฟอร์ม',
    'dash.channel.commandTitle': 'Command Deck',
    'dash.channel.commandDesc': 'ดูภาพรวมของช่องทางที่กำลังมีผล พร้อมรีเฟรชสถานะล่าสุดก่อนตัดสินใจ',
    'dash.channel.command.totalCommission': 'ค่าคอมมิชชั่นรวม',
    'dash.channel.command.settlements': 'รอบปิดยอด',
    'dash.channel.command.bindings': 'การผูกที่ใช้งาน',
    'dash.channel.refresh': 'รีเฟรชข้อมูล',
    'dash.channel.refreshing': 'กำลังรีเฟรช...',
    'dash.channel.binding.loading': 'กำลังโหลดข้อมูลการผูก...',
    'dash.channel.tabs.overview': 'ภาพรวม',
    'dash.channel.tabs.commissions': 'ค่าคอมมิชชั่น',
    'dash.channel.tabs.settlements': 'การปิดยอด',
    'dash.channel.tabs.binding': 'การผูกปัจจุบัน',
    'dash.channel.tabs.preview': 'พรีวิวกติกา',
    'dash.channel.tabs.adjustments': 'การปรับยอด',
    'dash.channel.metrics.pending': 'Pending',
    'dash.channel.metrics.pendingHint': 'ยอดที่รอผ่าน cooldown หรือ holdback',
    'dash.channel.metrics.earned': 'Earned',
    'dash.channel.metrics.earnedHint': 'ยอดที่พร้อมเข้าสู่รอบปิดยอดถัดไป',
    'dash.channel.metrics.settled': 'Settled',
    'dash.channel.metrics.settledHint': 'ยอดที่ปิดยอดสำเร็จแล้ว',
    'dash.channel.metrics.risk': 'Clawback',
    'dash.channel.metrics.riskHint': 'ยอดหักคืนที่ยังต้องเฝ้าระวัง',
    'dash.channel.status.active': 'ใช้งานอยู่',
    'dash.channel.status.pending': 'รอดำเนินการ',
    'dash.channel.status.earned': 'รับรู้แล้ว',
    'dash.channel.status.settlementInProgress': 'กำลังเข้าสู่รอบปิดยอด',
    'dash.channel.status.settled': 'ปิดยอดแล้ว',
    'dash.channel.status.reversed': 'ย้อนกลับแล้ว',
    'dash.channel.status.void': 'ยกเลิกผลกระทบ',
    'dash.channel.status.confirmed': 'ยืนยันแล้ว',
    'dash.channel.status.processing': 'กำลังประมวลผล',
    'dash.channel.status.closed': 'ปิดรอบแล้ว',
    'dash.channel.status.canceled': 'ยกเลิกรอบ',
    'dash.channel.status.generated': 'สร้างรอบแล้ว',
    'dash.channel.status.unknown': 'ไม่ทราบสถานะ',
    'dash.channel.overview.liveKicker': 'Active Bindings',
    'dash.channel.overview.liveTitle': 'ช่องทางที่กำลังส่งผลกับองค์กรนี้',
    'dash.channel.overview.liveDesc': 'ใช้มุมมองนี้ตรวจสอบว่าองค์กรผูกกับคู่ค้ารายใด โปรแกรมใด และเริ่มมีผลเมื่อใด',
    'dash.channel.overview.liveCta': 'เปิดการผูกปัจจุบัน',
    'dash.channel.overview.settlementKicker': 'Recent Batches',
    'dash.channel.overview.settlementTitle': 'รอบปิดยอดล่าสุด',
    'dash.channel.overview.settlementCta': 'ดูทั้งหมด',
    'dash.channel.overview.partnerKicker': 'Partner Roster',
    'dash.channel.overview.partnerTitle': 'คู่ค้าที่เกี่ยวข้อง',
    'dash.channel.overview.partnerDesc': 'สรุปรายชื่อคู่ค้าและระดับความเสี่ยงที่เกี่ยวข้องกับองค์กรนี้',
    'dash.channel.overview.snapshotTitle': 'ภาพรวมความเสี่ยงและยอดสะสม',
    'dash.channel.empty.bindingTitle': 'ยังไม่มีการผูกช่องทางที่ใช้งานอยู่',
    'dash.channel.empty.bindingDesc': 'เมื่อมีการลงทะเบียนหรือผูกช่องทางสำเร็จ มุมมองนี้จะแสดงพาร์ทเนอร์ โปรแกรม และช่วงเวลาที่เริ่มมีผล',
    'dash.channel.empty.settlementTitle': 'ยังไม่มีรายการปิดยอด',
    'dash.channel.empty.settlementDesc': 'เมื่อรอบปิดยอดแรกถูกสร้างและยืนยันแล้ว รายการ batch และยอดสุทธิจะปรากฏที่นี่',
    'dash.channel.empty.partnerDesc': 'ยังไม่พบคู่ค้าที่เชื่อมกับองค์กรนี้',
    'dash.channel.empty.commissionTitle': 'ยังไม่มีค่าคอมมิชชั่นให้ติดตาม',
    'dash.channel.empty.commissionDesc': 'หลังจากเกิด charge event และผ่านกติกา commission แล้ว รายการ ledger จะเริ่มแสดงในมุมมองนี้',
    'dash.channel.fields.source': 'Source Code',
    'dash.channel.fields.scope': 'Scope',
    'dash.channel.fields.effective': 'เริ่มมีผล',
    'dash.channel.fields.immediate': 'ทันที',
    'dash.channel.fields.commission': 'Commission',
    'dash.channel.fields.clawback': 'Clawback',
    'dash.channel.fields.periodEnd': 'สิ้นสุดรอบ',
    'dash.channel.fields.totalCommission': 'ค่าคอมมิชชั่นรวม',
    'dash.channel.fields.reversed': 'ยอดที่ถูกย้อนกลับ',
    'dash.channel.fields.appliedClawback': 'หักคืนที่ใช้แล้ว',
    'dash.channel.fields.rate': 'อัตรา',
    'dash.channel.fields.settleable': 'ยอดเข้าปิดได้',
    'dash.channel.fields.availableAt': 'พร้อมใช้งานเมื่อ',
    'dash.channel.fields.ledgerNo': 'Ledger No.',
    'dash.channel.fields.sourceCharge': 'Source Charge',
    'dash.channel.fields.netCollected': 'รายรับสุทธิ',
    'dash.channel.fields.holdback': 'ยอดกันสำรอง',
    'dash.channel.fields.earnedAt': 'รับรู้เมื่อ',
    'dash.channel.fields.settledAt': 'ปิดยอดเมื่อ',
    'dash.channel.fields.periodStart': 'เริ่มรอบ',
    'dash.channel.fields.grossCommission': 'ค่าคอมมิชชั่นก่อนหัก',
    'dash.channel.fields.grossClawback': 'ยอด clawback รวม',
    'dash.channel.fields.netAmount': 'ยอดสุทธิ',
    'dash.channel.fields.closedAt': 'ปิดรอบเมื่อ',
    'dash.channel.fields.reason': 'เหตุผล',
    'dash.channel.fields.lockedUntil': 'ล็อกจนถึง',
    'dash.channel.commissions.kicker': 'Commission Ledger',
    'dash.channel.commissions.title': 'ติดตาม ledger ตามสถานะจริง',
    'dash.channel.commissions.desc': 'เลือกสถานะเพื่อไล่ดูว่ารายการใดกำลังรอ รายการใดรับรู้แล้ว และรายการใดปิดยอดเรียบร้อย',
    'dash.channel.commissions.detailKicker': 'Selected Ledger',
    'dash.channel.commissions.detailDesc': 'เปิดรายละเอียด ledger เพื่อทบทวน source charge และมิติทางธุรกิจ',
    'dash.channel.commissions.dimensions': 'Business Dimensions',
    'dash.channel.commissions.detailEmptyTitle': 'เลือก ledger เพื่อดูรายละเอียด',
    'dash.channel.commissions.detailEmptyDesc': 'เมื่อมีรายการค่าคอมมิชชั่น คุณสามารถกดการ์ดด้านซ้ายเพื่อเปิดรายละเอียดเชิงลึกได้',
    'dash.channel.settlements.kicker': 'Settlement Timeline',
    'dash.channel.settlements.title': 'ดูรอบปิดยอดและยอดสุทธิรายคู่ค้า',
    'dash.channel.settlements.desc': 'มุมมองนี้ช่วยให้ทีมปฏิบัติการตรวจสอบสถานะ batch และภาพรวมสุทธิของแต่ละ partner ได้เร็ว',
    'dash.channel.settlements.detailKicker': 'Selected Batch',
    'dash.channel.settlements.detailDesc': 'ดูช่วงเวลาและยอดรวมของรอบปิดยอดที่เลือก',
    'dash.channel.settlements.snapshot': 'Statement Snapshot',
    'dash.channel.settlements.detailEmptyTitle': 'เลือก settlement เพื่อดูรายละเอียด',
    'dash.channel.settlements.detailEmptyDesc': 'เมื่อมีรายการปิดยอด คุณสามารถเปิดรายละเอียดของแต่ละ batch ได้ที่นี่',
    'dash.channel.binding.partner': 'Partner Binding',
    'dash.channel.binding.timelineKicker': 'Binding Timeline',
    'dash.channel.binding.timelineTitle': 'ลำดับเวลาของการผูกช่องทาง',
    'dash.channel.binding.timelineDesc': 'องค์กรนี้ถูกผูกเข้าโปรแกรมช่องทางจากเหตุการณ์ที่ผ่านการตรวจสอบแล้ว ทำให้ทุก charge ถัดไปสามารถคำนวณส่วนแบ่งได้อย่างสม่ำเสมอ',
    'dash.channel.binding.rulesKicker': 'Binding Rules',
    'dash.channel.binding.rulesTitle': 'กติกาการผูกที่ทีมต้องจำ',
    'dash.channel.binding.rule1Label': 'การลงทะเบียน',
    'dash.channel.binding.rule1Value': 'การผูกช่องทางเกิดแบบ best-effort หลังสร้างองค์กรสำเร็จ',
    'dash.channel.binding.rule2Label': 'การคุ้มครอง',
    'dash.channel.binding.rule2Value': 'charge ที่เกิดหลัง effective time เท่านั้นที่จะถูกนับเข้าคอมมิชชั่น',
    'dash.channel.binding.rule3Label': 'การย้อนกลับ',
    'dash.channel.binding.rule3Value': 'หาก charge ถูกย้อนหลังปิดยอด ระบบจะสร้าง clawback เข้ารอบถัดไป',
    'dash.channel.filters.all': 'ทั้งหมด',
    'dash.channel.filters.generated': 'สร้างแล้ว',
    'dash.channel.filters.pending': 'รอดำเนินการ',
    'dash.channel.filters.earned': 'รับรู้แล้ว',
    'dash.channel.filters.settlement_in_progress': 'กำลังปิดยอด',
    'dash.channel.filters.settled': 'ปิดยอดแล้ว',
    'dash.channel.filters.reversed': 'ย้อนกลับแล้ว',
    'dash.channel.filters.confirmed': 'ยืนยันแล้ว',
    'dash.channel.filters.processing': 'กำลังประมวลผล',
    'dash.channel.filters.closed': 'ปิดรอบแล้ว',
    'dash.channel.filters.canceled': 'ยกเลิก',
    'dash.channel.preview.kicker': 'Policy Preview',
    'dash.channel.preview.title': 'จำลองการ命中กติกาและผลลัพธ์ก่อน入账',
    'dash.channel.preview.desc': 'กรอกตัวเลขต้นทางเพื่อดูว่าระบบจะเลือก binding, policy, policy version และคำนวณ佣金อย่างไรโดยไม่สร้าง ledger จริง',
    'dash.channel.preview.fields.billableItem': 'Billable Item',
    'dash.channel.preview.fields.currency': 'Currency',
    'dash.channel.preview.fields.paidAmount': 'Paid Amount',
    'dash.channel.preview.fields.netCollected': 'Net Collected',
    'dash.channel.preview.fields.paymentFee': 'Payment Fee',
    'dash.channel.preview.fields.tax': 'Tax',
    'dash.channel.preview.fields.deliveryCost': 'Delivery Cost',
    'dash.channel.preview.fields.manualAdjustment': 'Manual Adjustment',
    'dash.channel.preview.run': 'รันพรีวิว',
    'dash.channel.preview.resultKicker': 'Preview Result',
    'dash.channel.preview.resultTitle': 'รอผลลัพธ์',
    'dash.channel.preview.result.mode': 'Mode',
    'dash.channel.preview.result.assignment': 'Assignment',
    'dash.channel.preview.result.rule': 'Matched Rule',
    'dash.channel.preview.result.commissionable': 'Commissionable',
    'dash.channel.preview.result.commission': 'Commission',
    'dash.channel.preview.result.holdback': 'Holdback',
    'dash.channel.preview.result.settleable': 'Settleable',
    'dash.channel.preview.result.profit': 'Profit',
    'dash.channel.preview.result.cost': 'Recognized Cost',
    'dash.channel.preview.emptyTitle': 'ยังไม่มีผลการพรีวิว',
    'dash.channel.preview.emptyDesc': 'กรอกตัวอย่างธุรกรรมทางซ้าย แล้วดูว่าระบบจะเลือกกติกาใดและคำนวณอย่างไร',
    'dash.channel.adjustments.kicker': 'Adjustment Ledger',
    'dash.channel.adjustments.title': 'จัดการ补差与追溯修正',
    'dash.channel.adjustments.desc': 'ใช้พื้นที่นี้สร้าง manual credit/debit หรือ reprice delta แล้วติดตามว่า adjustment เข้าสู่ settlement batch เมื่อใด',
    'dash.channel.adjustments.fields.partner': 'Partner ID',
    'dash.channel.adjustments.fields.program': 'Program ID',
    'dash.channel.adjustments.fields.type': 'Adjustment Type',
    'dash.channel.adjustments.fields.amount': 'Amount',
    'dash.channel.adjustments.fields.reason': 'Reason Code',
    'dash.channel.adjustments.fields.effective': 'Effective At',
    'dash.channel.adjustments.fields.batch': 'Applied Batch',
    'dash.channel.adjustments.create': 'สร้าง Adjustment',
    'dash.channel.adjustments.created': 'สร้าง adjustment สำเร็จ',
    'dash.channel.adjustments.listKicker': 'Adjustment Feed',
    'dash.channel.adjustments.listTitle': 'รายการ补差ล่าสุด',
    'dash.channel.adjustments.emptyTitle': 'ยังไม่มี adjustment',
    'dash.channel.adjustments.emptyDesc': 'เมื่อสร้าง补差或追溯修正后，รายการจะปรากฏที่นี่พร้อมสถานะและ批次关联',
  },
  zh: {
    'dash.credits': '剩余积分',
    'dash.creditReset': '每月重置',
    'dash.nav.home': '主页',
    'dash.nav.create': '创建内容',
    'dash.nav.library': '资料库',
    'dash.nav.history': '历史',
    'dash.nav.settings': '设置',
    'dash.upgrade.title': '升级到 Pro',
    'dash.upgrade.desc': '解锁社交媒体导出和评价海报功能',
    'dash.upgrade.btn': '升级 ฿249/月',
    'dash.upgrade.btn2': '升级',
    'dash.logout': '退出登录',
    'dash.welcome.label': '欢迎回来',
    'dash.welcome.prefix': '你好,',
    'dash.creditsLeft': '积分剩余',
    'dash.creditOverview': '本月积分概览',
    'dash.cr': '积分',
    'dash.resetDate': '重置日期: 2026年5月1日',
    'dash.feat.copy': 'AI 文案',
    'dash.feat.enhance': '图片优化',
    'dash.feat.social': '社交媒体',
    'dash.feat.collage': '多图拼接',
    'dash.free': '免费',
    'dash.perUse': '积分/次',
    'dash.quickActions': '快速开始',
    'dash.action.generate': 'AI 生成图片',
    'dash.action.generate.desc': '上传并优化食物图片',
    'dash.action.copy': 'AI 写广告语',
    'dash.action.copy.desc': '自动生成菜单描述',
    'dash.action.layout': '菜单排版设计',
    'dash.action.layout.desc': '创建精美菜单版式',
    'dash.action.social': '社交媒体导出',
    'dash.action.social.desc': 'Facebook, Instagram, LINE OA',
    'dash.action.poster': '评价海报',
    'dash.action.poster.desc': '根据客户评价生成海报',
    'dash.action.festival': '泰国节日模板',
    'dash.action.festival.desc': '宋干节 春节 水灯节',
    'dash.recentActivity': '最近活动',
    'dash.noActivity': '还没有活动，开始创建内容吧！',
    'dash.create.title': '创建内容',
    'dash.create.desc': '从主页选择功能开始创建',
    'dash.create.back': '返回主页',
    'dash.history.title': '使用历史',
    'dash.settings.title': '账户设置',
    'dash.settings.identity.title': '餐厅身份',
    'dash.settings.identity.namePlaceholder': '您的姓名',
    'dash.settings.identity.restaurantPlaceholder': '餐厅名称',
    'dash.settings.security.title': '账户安全',
    'dash.settings.security.emailHint': '电子邮件地址不能直接更改。如需帮助请联系客服。',
    'dash.settings.preferences.title': '偏好设置',
    'dash.settings.plan.activeStatus': '生效中',
    'dash.settings.saveBar.title': '有未保存的更改',
    'dash.settings.saveBar.desc': '应用您的更新以继续',
    'dash.settings.saveBar.discard': '丢弃',
    'dash.settings.saveBar.save': '保存更改',
    'dash.settings.saveBar.saving': '保存中...',
    'dash.settings.success': '配置更新成功',
    'dash.settings.error': '配置更新失败',
    'dash.settings.name': '店铺名称',
    'dash.settings.restaurant': '餐厅名称',
    'dash.settings.email': '电子邮箱',
    'dash.settings.lang': '语言',
    'dash.settings.save': '保存',
    'dash.settings.plan': '当前套餐',
    'dash.settings.free': '永久免费',
    'dash.toast.used': '消耗积分',
    'dash.toast.remain': '剩余:',
    'dash.create.heroTitle': '为门店选择下一步创作流程',
    'dash.create.heroDesc': '按任务进入对应工作流，直接去 Studio 生成，或者进入资料与历史中心继续处理。',
    'dash.route.referral': '推广中心',
    'dash.route.channel': '渠道分佣',
    'dash.home.heroTitle': '在一个工作台里完成菜单内容生成与增长运营',
    'dash.home.heroDesc': '先进入 Studio 生成内容，再无缝流转到资料库、历史中心和推广中心，不必在多个割裂页面来回跳转。',
    'dash.home.primaryCta': '进入 Studio',
    'dash.home.secondaryCta': '打开资料库',
    'dash.home.referralTitle': '增长与推广中心',
    'dash.home.referralDesc': '集中查看邀请链接、转化数据、待结算佣金和可兑换资产，让增长链路更清楚。',
    'dash.home.channelTitle': '渠道分佣工作台',
    'dash.home.channelDesc': '集中查看渠道绑定、佣金账本、追回金额和结算批次，形成完整分佣视图。',
    'dash.home.activityViewAll': '查看全部',
    'dash.home.studioTitle': 'Studio',
    'dash.home.libraryTitle': '资料库',
    'dash.home.libraryDesc': '管理原始素材、生成结果与已发布资产，在更宽的空间里完成筛选和处理。',
    'dash.home.settingsDesc': '在 Dashboard 内完成店铺资料、语言偏好与账号套餐的统一维护。',
    'dash.create.workflow.studioTitle': 'AI Studio',
    'dash.create.workflow.studioDesc': '在专属工作台中生成、精修并挑选最终的菜品图片结果。',
    'dash.create.workflow.libraryTitle': 'Asset Library',
    'dash.create.workflow.libraryDesc': '查看已上传素材、生成结果和发布资产，并在更自适应的管理空间中继续处理。',
    'dash.create.workflow.historyTitle': 'History Center',
    'dash.create.workflow.historyDesc': '通过可路由化的页面查看账单流、任务历史与操作审计，不再困在单页切换里。',
    'dash.create.stepLabel': '步骤',
    'dash.create.flowTitle': '生产流程',
    'dash.create.flowDesc': '新的 Dashboard 负责路由与管理，Studio 负责真正的内容生产，不再让所有功能挤在一个平面里。',
    'dash.create.adaptiveTitle': '自适应工作区',
    'dash.create.adaptiveDesc': 'Library、History、Referral 这类宽页面不应该再被旧版 Dashboard 的窄容器压瘪。',
    'dash.channel.loadError': '渠道数据加载失败',
    'dash.channel.kicker': 'Channel Revenue Share',
    'dash.channel.heroTitle': '在一个工作台里掌控渠道绑定、佣金与结算',
    'dash.channel.heroDesc': '这个业务域把渠道绑定、佣金 ledger、clawback 和结算批次聚合成前台可读的控制台视图，让团队不用理解平台内部账本也能快速判断状态。',
    'dash.channel.commandTitle': 'Command Deck',
    'dash.channel.commandDesc': '在操作前先确认当前绑定、累计佣金与结算进度，避免在多个页面来回跳转。',
    'dash.channel.command.totalCommission': '累计佣金',
    'dash.channel.command.settlements': '结算批次',
    'dash.channel.command.bindings': '生效绑定',
    'dash.channel.refresh': '刷新数据',
    'dash.channel.refreshing': '刷新中...',
    'dash.channel.binding.loading': '加载绑定数据中...',
    'dash.channel.tabs.overview': '总览',
    'dash.channel.tabs.commissions': '佣金账本',
    'dash.channel.tabs.settlements': '结算批次',
    'dash.channel.tabs.binding': '当前绑定',
    'dash.channel.tabs.preview': '规则预演',
    'dash.channel.tabs.adjustments': '补差调整',
    'dash.channel.metrics.pending': 'Pending',
    'dash.channel.metrics.pendingHint': '仍在 cooldown 或 holdback 阶段的佣金',
    'dash.channel.metrics.earned': 'Earned',
    'dash.channel.metrics.earnedHint': '已经成熟，等待进入结算批次的佣金',
    'dash.channel.metrics.settled': 'Settled',
    'dash.channel.metrics.settledHint': '已经结算完成的净额',
    'dash.channel.metrics.risk': 'Clawback',
    'dash.channel.metrics.riskHint': '待处理的追回金额，需要运营关注',
    'dash.channel.status.active': '生效中',
    'dash.channel.status.pending': '待处理',
    'dash.channel.status.earned': '已成熟',
    'dash.channel.status.settlementInProgress': '结算中',
    'dash.channel.status.settled': '已结算',
    'dash.channel.status.reversed': '已冲回',
    'dash.channel.status.void': '已作废',
    'dash.channel.status.confirmed': '已确认',
    'dash.channel.status.processing': '处理中',
    'dash.channel.status.closed': '已关闭',
    'dash.channel.status.canceled': '已取消',
    'dash.channel.status.generated': '已生成',
    'dash.channel.status.unknown': '未知状态',
    'dash.channel.overview.liveKicker': 'Active Bindings',
    'dash.channel.overview.liveTitle': '当前对组织生效的渠道关系',
    'dash.channel.overview.liveDesc': '这里直接展示组织当前绑定到了哪个渠道伙伴、哪个计划，以及这条绑定从何时开始生效。',
    'dash.channel.overview.liveCta': '查看当前绑定',
    'dash.channel.overview.settlementKicker': 'Recent Batches',
    'dash.channel.overview.settlementTitle': '最近结算批次',
    'dash.channel.overview.settlementCta': '查看全部',
    'dash.channel.overview.partnerKicker': 'Partner Roster',
    'dash.channel.overview.partnerTitle': '关联渠道伙伴',
    'dash.channel.overview.partnerDesc': '按伙伴维度查看当前组织挂靠的渠道主体与风险等级。',
    'dash.channel.overview.snapshotTitle': '累计收入与风险快照',
    'dash.channel.empty.bindingTitle': '还没有生效中的渠道绑定',
    'dash.channel.empty.bindingDesc': '当注册链路或人工绑定流程成功后，这里会显示伙伴、计划和生效时间，方便业务同学核对来源。',
    'dash.channel.empty.settlementTitle': '还没有结算批次',
    'dash.channel.empty.settlementDesc': '第一批结算生成并确认后，这里会开始显示批次编号、净额和周期信息。',
    'dash.channel.empty.partnerDesc': '当前组织尚未关联到任何渠道伙伴。',
    'dash.channel.empty.commissionTitle': '还没有可追踪的佣金记录',
    'dash.channel.empty.commissionDesc': '当产品侧上报有效 charge 并匹配到佣金策略后，这里会开始出现对应 ledger。',
    'dash.channel.fields.source': '来源码',
    'dash.channel.fields.scope': '绑定范围',
    'dash.channel.fields.effective': '生效时间',
    'dash.channel.fields.immediate': '立即生效',
    'dash.channel.fields.commission': '佣金金额',
    'dash.channel.fields.clawback': '追回金额',
    'dash.channel.fields.periodEnd': '周期结束',
    'dash.channel.fields.totalCommission': '累计佣金',
    'dash.channel.fields.reversed': '已冲回金额',
    'dash.channel.fields.appliedClawback': '已应用追回',
    'dash.channel.fields.rate': '佣金比例',
    'dash.channel.fields.settleable': '可结算净额',
    'dash.channel.fields.availableAt': '可成熟时间',
    'dash.channel.fields.ledgerNo': '账本编号',
    'dash.channel.fields.sourceCharge': '来源扣费',
    'dash.channel.fields.netCollected': '净收款',
    'dash.channel.fields.holdback': '保留金',
    'dash.channel.fields.earnedAt': '成熟时间',
    'dash.channel.fields.settledAt': '结算时间',
    'dash.channel.fields.periodStart': '周期开始',
    'dash.channel.fields.grossCommission': '毛佣金',
    'dash.channel.fields.grossClawback': '毛追回',
    'dash.channel.fields.netAmount': '净额',
    'dash.channel.fields.closedAt': '关闭时间',
    'dash.channel.fields.reason': '原因',
    'dash.channel.fields.lockedUntil': '锁定到',
    'dash.channel.commissions.kicker': 'Commission Ledger',
    'dash.channel.commissions.title': '按真实状态查看佣金 ledger',
    'dash.channel.commissions.desc': '按状态筛选 ledger，快速区分哪些还在冷却期、哪些已经成熟、哪些已经进入结算或被冲回。',
    'dash.channel.commissions.detailKicker': 'Selected Ledger',
    'dash.channel.commissions.detailDesc': '展开查看来源扣费、持有保留金和业务维度字段。',
    'dash.channel.commissions.dimensions': '业务维度',
    'dash.channel.commissions.detailEmptyTitle': '选择一条佣金记录查看细节',
    'dash.channel.commissions.detailEmptyDesc': '左侧出现 ledger 后，点击任意卡片即可在这里看到更完整的账本信息。',
    'dash.channel.settlements.kicker': 'Settlement Timeline',
    'dash.channel.settlements.title': '查看每个批次的净额与周期',
    'dash.channel.settlements.desc': '把批次状态、伙伴净额和周期范围集中到一个页面，方便财务与运营同步。',
    'dash.channel.settlements.detailKicker': 'Selected Batch',
    'dash.channel.settlements.detailDesc': '这里展示所选批次的周期边界、毛佣金、追回和最终净额。',
    'dash.channel.settlements.snapshot': '结算快照',
    'dash.channel.settlements.detailEmptyTitle': '选择一个结算批次查看详情',
    'dash.channel.settlements.detailEmptyDesc': '当左侧有结算记录时，点击任意卡片即可在这里查看批次细节。',
    'dash.channel.binding.partner': '绑定伙伴',
    'dash.channel.binding.timelineKicker': 'Binding Timeline',
    'dash.channel.binding.timelineTitle': '渠道绑定时间线',
    'dash.channel.binding.timelineDesc': '当前组织的绑定已经通过注册或运营动作落地，从生效时间开始，后续产品消费都会进入同一条分佣链路。',
    'dash.channel.binding.rulesKicker': 'Binding Rules',
    'dash.channel.binding.rulesTitle': '团队需要记住的三条规则',
    'dash.channel.binding.rule1Label': '注册接入',
    'dash.channel.binding.rule1Value': '组织创建成功后，渠道绑定以 best-effort 方式跟进，不回滚注册成功结果。',
    'dash.channel.binding.rule2Label': '计佣边界',
    'dash.channel.binding.rule2Value': '只有生效时间之后的有效 charge 才会进入佣金计算。',
    'dash.channel.binding.rule3Label': '退款冲回',
    'dash.channel.binding.rule3Value': '如果已结算 charge 发生退款，系统会生成 clawback 进入后续批次。',
    'dash.channel.filters.all': '全部',
    'dash.channel.filters.generated': '已生成',
    'dash.channel.filters.pending': '待处理',
    'dash.channel.filters.earned': '已成熟',
    'dash.channel.filters.settlement_in_progress': '结算中',
    'dash.channel.filters.settled': '已结算',
    'dash.channel.filters.reversed': '已冲回',
    'dash.channel.filters.confirmed': '已确认',
    'dash.channel.filters.processing': '处理中',
    'dash.channel.filters.closed': '已关闭',
    'dash.channel.filters.canceled': '已取消',
    'dash.channel.preview.kicker': 'Policy Preview',
    'dash.channel.preview.title': '在落账前预演规则命中与净利润分佣',
    'dash.channel.preview.desc': '输入一笔模拟 charge，直接查看系统会命中哪条 binding、哪版 policy、哪层 assignment，以及最终佣金结果。',
    'dash.channel.preview.fields.billableItem': '计费项',
    'dash.channel.preview.fields.currency': '币种',
    'dash.channel.preview.fields.paidAmount': '实付金额',
    'dash.channel.preview.fields.netCollected': '净收款',
    'dash.channel.preview.fields.paymentFee': '支付手续费',
    'dash.channel.preview.fields.tax': '税费',
    'dash.channel.preview.fields.deliveryCost': '履约成本',
    'dash.channel.preview.fields.manualAdjustment': '人工调整',
    'dash.channel.preview.run': '运行预演',
    'dash.channel.preview.resultKicker': 'Preview Result',
    'dash.channel.preview.resultTitle': '等待预演结果',
    'dash.channel.preview.result.mode': '命中模式',
    'dash.channel.preview.result.assignment': '命中层级',
    'dash.channel.preview.result.rule': '命中规则',
    'dash.channel.preview.result.commissionable': '可计佣基数',
    'dash.channel.preview.result.commission': '佣金金额',
    'dash.channel.preview.result.holdback': '保留金',
    'dash.channel.preview.result.settleable': '可结算净额',
    'dash.channel.preview.result.profit': '可分配利润',
    'dash.channel.preview.result.cost': '已确认成本',
    'dash.channel.preview.emptyTitle': '还没有预演结果',
    'dash.channel.preview.emptyDesc': '在左侧输入一笔模拟交易后，这里会展示规则命中链路、利润快照和预演金额。',
    'dash.channel.adjustments.kicker': 'Adjustment Ledger',
    'dash.channel.adjustments.title': '管理补差与追溯修正',
    'dash.channel.adjustments.desc': '这里用于创建 manual credit / debit、重定价差额和成本补差，并跟踪它们何时进入结算批次。',
    'dash.channel.adjustments.fields.partner': '渠道伙伴 ID',
    'dash.channel.adjustments.fields.program': '渠道计划 ID',
    'dash.channel.adjustments.fields.type': '调整类型',
    'dash.channel.adjustments.fields.amount': '调整金额',
    'dash.channel.adjustments.fields.reason': '原因码',
    'dash.channel.adjustments.fields.effective': '生效时间',
    'dash.channel.adjustments.fields.batch': '已应用批次',
    'dash.channel.adjustments.create': '创建 Adjustment',
    'dash.channel.adjustments.created': 'Adjustment 已创建',
    'dash.channel.adjustments.listKicker': 'Adjustment Feed',
    'dash.channel.adjustments.listTitle': '最近补差记录',
    'dash.channel.adjustments.emptyTitle': '还没有补差记录',
    'dash.channel.adjustments.emptyDesc': '创建补差或追溯修正后，这里会展示金额、状态和进入批次的情况。',
  },
  en: {
    'dash.credits': 'Credits remaining',
    'dash.creditReset': 'Resets monthly',
    'dash.nav.home': 'Home',
    'dash.nav.create': 'Create',
    'dash.nav.library': 'Library',
    'dash.nav.history': 'History',
    'dash.nav.settings': 'Settings',
    'dash.upgrade.title': 'Upgrade to Pro',
    'dash.upgrade.desc': 'Unlock social media export and review posters',
    'dash.upgrade.btn': 'Upgrade ฿249/mo',
    'dash.upgrade.btn2': 'Upgrade',
    'dash.logout': 'Log out',
    'dash.welcome.label': 'Welcome back',
    'dash.welcome.prefix': 'Hello,',
    'dash.creditsLeft': 'credits remaining',
    'dash.creditOverview': "This month's credits",
    'dash.cr': 'cr',
    'dash.resetDate': 'Resets May 1, 2026',
    'dash.feat.copy': 'AI Copy',
    'dash.feat.enhance': 'Enhancement',
    'dash.feat.social': 'Social Export',
    'dash.feat.collage': 'Collage',
    'dash.free': 'Free',
    'dash.perUse': 'cr/use',
    'dash.quickActions': 'Quick Actions',
    'dash.action.generate': 'AI Image Generation',
    'dash.action.generate.desc': 'Upload and enhance food photos',
    'dash.action.copy': 'AI Copywriting',
    'dash.action.copy.desc': 'Auto-generate menu descriptions',
    'dash.action.layout': 'Menu Layout Design',
    'dash.action.layout.desc': 'Create beautiful menu layouts',
    'dash.action.social': 'Social Media Export',
    'dash.action.social.desc': 'Facebook, Instagram, LINE OA',
    'dash.action.poster': 'Review Poster',
    'dash.action.poster.desc': 'Generate posters from customer reviews',
    'dash.action.festival': 'Thai Festival Templates',
    'dash.action.festival.desc': 'Songkran, CNY, Loy Krathong',
    'dash.recentActivity': 'Recent Activity',
    'dash.noActivity': 'No activity yet — start creating content!',
    'dash.create.title': 'Create Content',
    'dash.create.desc': 'Choose a feature from home to start creating',
    'dash.create.back': 'Back to Home',
    'dash.history.title': 'Usage History',
    'dash.settings.title': 'Account Settings',
    'dash.settings.identity.title': 'Restaurant Identity',
    'dash.settings.identity.namePlaceholder': 'Your Name',
    'dash.settings.identity.restaurantPlaceholder': 'Restaurant Name',
    'dash.settings.security.title': 'Account Security',
    'dash.settings.security.emailHint': 'Email address cannot be changed directly. Contact support if needed.',
    'dash.settings.preferences.title': 'Preferences',
    'dash.settings.plan.activeStatus': 'Active Status',
    'dash.settings.saveBar.title': 'Unsaved changes',
    'dash.settings.saveBar.desc': 'Apply your updates to continue',
    'dash.settings.saveBar.discard': 'Discard',
    'dash.settings.saveBar.save': 'Save Changes',
    'dash.settings.saveBar.saving': 'Saving...',
    'dash.settings.success': 'Profile updated successfully',
    'dash.settings.error': 'Failed to update profile',
    'dash.settings.name': 'Store name',
    'dash.settings.restaurant': 'Restaurant name',
    'dash.settings.email': 'Email',
    'dash.settings.lang': 'Language',
    'dash.settings.save': 'Save',
    'dash.settings.plan': 'Current plan',
    'dash.settings.free': 'Free forever',
    'dash.toast.used': 'Credits used',
    'dash.toast.remain': 'Remaining:',
    'dash.create.heroTitle': 'Choose the next workflow for your store',
    'dash.create.heroDesc': 'Jump into Studio for image generation, or open the right management center for your next action.',
    'dash.route.referral': 'Referral Center',
    'dash.route.channel': 'Channel Revenue Share',
    'dash.home.heroTitle': 'Run menu creation and growth from one workspace',
    'dash.home.heroDesc': 'Launch Studio for production, then move through Library, History, and Referral without dropping into disconnected views.',
    'dash.home.primaryCta': 'Open Studio',
    'dash.home.secondaryCta': 'Open Library',
    'dash.home.referralTitle': 'Growth & Referral Center',
    'dash.home.referralDesc': 'Track invite links, conversions, pending commissions, and redeemable assets inside one focused workspace.',
    'dash.home.channelTitle': 'Channel Revenue Desk',
    'dash.home.channelDesc': 'Review bindings, commission ledgers, clawbacks, and settlement batches without leaving the dashboard flow.',
    'dash.home.activityViewAll': 'View All',
    'dash.home.studioTitle': 'Studio',
    'dash.home.libraryTitle': 'Library',
    'dash.home.libraryDesc': 'Manage source materials, generated assets, and published outputs with a wider adaptive workspace.',
    'dash.home.settingsDesc': 'Update business profile, language preferences, and account plan settings without leaving the dashboard flow.',
    'dash.create.workflow.studioTitle': 'AI Studio',
    'dash.create.workflow.studioDesc': 'Generate, refine, and select polished food images inside the dedicated Studio workspace.',
    'dash.create.workflow.libraryTitle': 'Asset Library',
    'dash.create.workflow.libraryDesc': 'Review uploaded photos, generated results, and shared assets in a wider adaptive manager.',
    'dash.create.workflow.historyTitle': 'History Center',
    'dash.create.workflow.historyDesc': 'Jump into billing flow, job history, and operation audit records with route-level deep links.',
    'dash.create.stepLabel': 'Step',
    'dash.create.flowTitle': 'Production Flow',
    'dash.create.flowDesc': 'Dashboard now handles routing and management, while Studio stays focused on the actual generation workflow.',
    'dash.create.adaptiveTitle': 'Adaptive Workspace',
    'dash.create.adaptiveDesc': 'Wide management pages like Library, History, and Referral should no longer be constrained by the old narrow dashboard shell.',
    'dash.channel.loadError': 'Failed to load channel data',
    'dash.channel.kicker': 'Channel Revenue Share',
    'dash.channel.heroTitle': 'Track bindings, commission ledgers, and settlements in one workspace',
    'dash.channel.heroDesc': 'This business surface reshapes platform-owned channel accounting into an operational dashboard so the team can understand live partner status without reading raw settlement internals.',
    'dash.channel.commandTitle': 'Command Deck',
    'dash.channel.commandDesc': 'Use this quick summary to confirm active bindings, total commission, and settlement progress before taking action.',
    'dash.channel.command.totalCommission': 'Total commission',
    'dash.channel.command.settlements': 'Settlement batches',
    'dash.channel.command.bindings': 'Active bindings',
    'dash.channel.refresh': 'Refresh data',
    'dash.channel.refreshing': 'Refreshing...',
    'dash.channel.binding.loading': 'Loading Binding Data...',
    'dash.channel.tabs.overview': 'Overview',
    'dash.channel.tabs.commissions': 'Commissions',
    'dash.channel.tabs.settlements': 'Settlements',
    'dash.channel.tabs.binding': 'Current Binding',
    'dash.channel.tabs.preview': 'Policy Preview',
    'dash.channel.tabs.adjustments': 'Adjustments',
    'dash.channel.metrics.pending': 'Pending',
    'dash.channel.metrics.pendingHint': 'Commission still sitting in cooldown or holdback.',
    'dash.channel.metrics.earned': 'Earned',
    'dash.channel.metrics.earnedHint': 'Mature commission ready for the next settlement batch.',
    'dash.channel.metrics.settled': 'Settled',
    'dash.channel.metrics.settledHint': 'Net amounts that already closed successfully.',
    'dash.channel.metrics.risk': 'Clawback',
    'dash.channel.metrics.riskHint': 'Pending clawback exposure to watch closely.',
    'dash.channel.status.active': 'Active',
    'dash.channel.status.pending': 'Pending',
    'dash.channel.status.earned': 'Earned',
    'dash.channel.status.settlementInProgress': 'Settlement In Progress',
    'dash.channel.status.settled': 'Settled',
    'dash.channel.status.reversed': 'Reversed',
    'dash.channel.status.void': 'Void',
    'dash.channel.status.confirmed': 'Confirmed',
    'dash.channel.status.processing': 'Processing',
    'dash.channel.status.closed': 'Closed',
    'dash.channel.status.canceled': 'Canceled',
    'dash.channel.status.generated': 'Generated',
    'dash.channel.status.unknown': 'Unknown',
    'dash.channel.overview.liveKicker': 'Active Bindings',
    'dash.channel.overview.liveTitle': 'Bindings currently shaping this organization',
    'dash.channel.overview.liveDesc': 'Review which partner and program this organization is attached to, and when the relationship became effective.',
    'dash.channel.overview.liveCta': 'Open bindings',
    'dash.channel.overview.settlementKicker': 'Recent Batches',
    'dash.channel.overview.settlementTitle': 'Latest settlement movement',
    'dash.channel.overview.settlementCta': 'View all',
    'dash.channel.overview.partnerKicker': 'Partner Roster',
    'dash.channel.overview.partnerTitle': 'Connected partners',
    'dash.channel.overview.partnerDesc': 'A quick roster of partner entities tied to this organization, including risk posture.',
    'dash.channel.overview.snapshotTitle': 'Accumulated revenue and exposure',
    'dash.channel.empty.bindingTitle': 'No active channel binding yet',
    'dash.channel.empty.bindingDesc': 'After signup follow-up or manual binding succeeds, this view shows the partner, program, and effective timing.',
    'dash.channel.empty.settlementTitle': 'No settlement batches yet',
    'dash.channel.empty.settlementDesc': 'Once the first batch is generated and confirmed, the cycle, net amount, and batch id appear here.',
    'dash.channel.empty.partnerDesc': 'No partner entity is currently attached to this organization.',
    'dash.channel.empty.commissionTitle': 'No commission ledger to track yet',
    'dash.channel.empty.commissionDesc': 'Ledger entries appear here after product charges are reported and matched to an active commission policy.',
    'dash.channel.fields.source': 'Source code',
    'dash.channel.fields.scope': 'Scope',
    'dash.channel.fields.effective': 'Effective at',
    'dash.channel.fields.immediate': 'Immediate',
    'dash.channel.fields.commission': 'Commission',
    'dash.channel.fields.clawback': 'Clawback',
    'dash.channel.fields.periodEnd': 'Period end',
    'dash.channel.fields.totalCommission': 'Total commission',
    'dash.channel.fields.reversed': 'Reversed amount',
    'dash.channel.fields.appliedClawback': 'Applied clawback',
    'dash.channel.fields.rate': 'Rate',
    'dash.channel.fields.settleable': 'Settleable',
    'dash.channel.fields.availableAt': 'Available at',
    'dash.channel.fields.ledgerNo': 'Ledger no.',
    'dash.channel.fields.sourceCharge': 'Source charge',
    'dash.channel.fields.netCollected': 'Net collected',
    'dash.channel.fields.holdback': 'Holdback',
    'dash.channel.fields.earnedAt': 'Earned at',
    'dash.channel.fields.settledAt': 'Settled at',
    'dash.channel.fields.periodStart': 'Period start',
    'dash.channel.fields.grossCommission': 'Gross commission',
    'dash.channel.fields.grossClawback': 'Gross clawback',
    'dash.channel.fields.netAmount': 'Net amount',
    'dash.channel.fields.closedAt': 'Closed at',
    'dash.channel.fields.reason': 'Reason',
    'dash.channel.fields.lockedUntil': 'Locked until',
    'dash.channel.commissions.kicker': 'Commission Ledger',
    'dash.channel.commissions.title': 'Read every ledger by its real lifecycle status',
    'dash.channel.commissions.desc': 'Filter the ledger to separate cooling entries, earned entries, settled entries, and reversals without losing operational context.',
    'dash.channel.commissions.detailKicker': 'Selected Ledger',
    'dash.channel.commissions.detailDesc': 'Inspect the charge source, holdback, and attached business dimensions.',
    'dash.channel.commissions.dimensions': 'Business dimensions',
    'dash.channel.commissions.detailEmptyTitle': 'Pick a ledger to inspect',
    'dash.channel.commissions.detailEmptyDesc': 'As commission records appear, select any card on the left to open the richer detail panel here.',
    'dash.channel.settlements.kicker': 'Settlement Timeline',
    'dash.channel.settlements.title': 'Review partner net amounts across settlement batches',
    'dash.channel.settlements.desc': 'This view keeps batch state, partner net value, and period boundaries together for operations and finance.',
    'dash.channel.settlements.detailKicker': 'Selected Batch',
    'dash.channel.settlements.detailDesc': 'Inspect period boundaries, gross commission, clawback, and final net amount for the selected batch.',
    'dash.channel.settlements.snapshot': 'Statement snapshot',
    'dash.channel.settlements.detailEmptyTitle': 'Pick a settlement to inspect',
    'dash.channel.settlements.detailEmptyDesc': 'Select a settlement card on the left to open batch details and statement context here.',
    'dash.channel.binding.partner': 'Partner binding',
    'dash.channel.binding.timelineKicker': 'Binding Timeline',
    'dash.channel.binding.timelineTitle': 'How the current binding took effect',
    'dash.channel.binding.timelineDesc': 'The organization now sits under a verified partner binding, so future product charges can flow into one consistent revenue-share path.',
    'dash.channel.binding.rulesKicker': 'Binding Rules',
    'dash.channel.binding.rulesTitle': 'Three rules the team should remember',
    'dash.channel.binding.rule1Label': 'Signup follow-up',
    'dash.channel.binding.rule1Value': 'Binding runs as a best-effort follow-up after organization creation and never rolls back signup success.',
    'dash.channel.binding.rule2Label': 'Commission boundary',
    'dash.channel.binding.rule2Value': 'Only effective charges after the binding start time enter commission accounting.',
    'dash.channel.binding.rule3Label': 'Refund reversal',
    'dash.channel.binding.rule3Value': 'If a settled charge gets refunded, the system creates a clawback for a later batch.',
    'dash.channel.filters.all': 'All',
    'dash.channel.filters.generated': 'Generated',
    'dash.channel.filters.pending': 'Pending',
    'dash.channel.filters.earned': 'Earned',
    'dash.channel.filters.settlement_in_progress': 'Settlement In Progress',
    'dash.channel.filters.settled': 'Settled',
    'dash.channel.filters.reversed': 'Reversed',
    'dash.channel.filters.confirmed': 'Confirmed',
    'dash.channel.filters.processing': 'Processing',
    'dash.channel.filters.closed': 'Closed',
    'dash.channel.filters.canceled': 'Canceled',
    'dash.channel.preview.kicker': 'Policy Preview',
    'dash.channel.preview.title': 'Dry-run rule matching before a ledger is created',
    'dash.channel.preview.desc': 'Simulate a charge to inspect the matched binding, policy version, assignment level, profit snapshot, and final commission result without writing a real ledger.',
    'dash.channel.preview.fields.billableItem': 'Billable item',
    'dash.channel.preview.fields.currency': 'Currency',
    'dash.channel.preview.fields.paidAmount': 'Paid amount',
    'dash.channel.preview.fields.netCollected': 'Net collected',
    'dash.channel.preview.fields.paymentFee': 'Payment fee',
    'dash.channel.preview.fields.tax': 'Tax',
    'dash.channel.preview.fields.deliveryCost': 'Delivery cost',
    'dash.channel.preview.fields.manualAdjustment': 'Manual adjustment',
    'dash.channel.preview.run': 'Run preview',
    'dash.channel.preview.resultKicker': 'Preview Result',
    'dash.channel.preview.resultTitle': 'Waiting for preview',
    'dash.channel.preview.result.mode': 'Mode',
    'dash.channel.preview.result.assignment': 'Assignment',
    'dash.channel.preview.result.rule': 'Matched rule',
    'dash.channel.preview.result.commissionable': 'Commissionable',
    'dash.channel.preview.result.commission': 'Commission',
    'dash.channel.preview.result.holdback': 'Holdback',
    'dash.channel.preview.result.settleable': 'Settleable',
    'dash.channel.preview.result.profit': 'Distributable profit',
    'dash.channel.preview.result.cost': 'Recognized cost',
    'dash.channel.preview.emptyTitle': 'No preview result yet',
    'dash.channel.preview.emptyDesc': 'Enter a simulated charge on the left to inspect the full rule-resolution and profit-sharing outcome here.',
    'dash.channel.adjustments.kicker': 'Adjustment Ledger',
    'dash.channel.adjustments.title': 'Manage true-ups and retrospective adjustments',
    'dash.channel.adjustments.desc': 'Create manual credits, debits, repricing deltas, and cost true-ups, then track when they flow into settlement batches.',
    'dash.channel.adjustments.fields.partner': 'Partner ID',
    'dash.channel.adjustments.fields.program': 'Program ID',
    'dash.channel.adjustments.fields.type': 'Adjustment type',
    'dash.channel.adjustments.fields.amount': 'Amount',
    'dash.channel.adjustments.fields.reason': 'Reason code',
    'dash.channel.adjustments.fields.effective': 'Effective at',
    'dash.channel.adjustments.fields.batch': 'Applied batch',
    'dash.channel.adjustments.create': 'Create adjustment',
    'dash.channel.adjustments.created': 'Adjustment created',
    'dash.channel.adjustments.listKicker': 'Adjustment Feed',
    'dash.channel.adjustments.listTitle': 'Latest true-up entries',
    'dash.channel.adjustments.emptyTitle': 'No adjustments yet',
    'dash.channel.adjustments.emptyDesc': 'New manual or retrospective adjustments appear here with their status and settlement linkage.',
  },
};

export function getDashboardText(lang: string, key: string): string {
  const normalized = lang === 'th' || lang === 'zh' || lang === 'en' ? lang : 'en';
  return dashboardCopy[normalized][key] || dashboardCopy.en[key] || key;
}
