export const dashboardCopy: Record<'th' | 'zh' | 'en', Record<string, string>> = {
  th: {
    'dash.credits': 'เครดิตคงเหลือ',
    'dash.creditReset': 'รีเซ็ตทุกสิ้นเดือน',
    'dash.nav.home': 'หน้าหลัก',
    'dash.nav.create': 'สร้างเนื้อหา',
    'dash.nav.library': 'คลังผลงาน',
    'dash.nav.history': 'ประวัติ',
    'dash.nav.settings': 'ตั้งค่า',
    'dash.upgrade.title': 'อัปเกรดเป็น Pro',
    'dash.upgrade.desc': 'ปลดล็อคฟีเจอร์โซเชียลมีเดียและโปสเตอร์รีวิว',
    'dash.upgrade.btn': 'อัปเกรด ฿249/เดือน',
    'dash.upgrade.btn2': 'อัปเกรด',
    'dash.logout': 'ออกจากระบบ',
    'dash.welcome.label': 'ยินดีต้อนรับกลับมา',
    'dash.welcome.prefix': 'สวัสดี,',
    'dash.creditsLeft': 'เครดิตคงเหลือ',
    'dash.creditOverview': 'สรุปเครดิตเดือนนี้',
    'dash.cr': 'cr',
    'dash.resetDate': 'รีเซ็ต 1 พ.ค. 2026',
    'dash.feat.copy': 'AI คัดลอก',
    'dash.feat.enhance': 'ปรับปรุงภาพ',
    'dash.feat.social': 'โซเชียลมีเดีย',
    'dash.feat.collage': 'คอลลาจ',
    'dash.free': 'ฟรี',
    'dash.perUse': 'cr/ครั้ง',
    'dash.quickActions': 'เริ่มสร้างเลย',
    'dash.action.generate': 'สร้างภาพ AI',
    'dash.action.generate.desc': 'อัปโหลดและปรับปรุงภาพอาหาร',
    'dash.action.copy': 'AI เขียนคำโฆษณา',
    'dash.action.copy.desc': 'สร้างคำอธิบายเมนูอัตโนมัติ',
    'dash.action.layout': 'จัดเลย์เอาต์เมนู',
    'dash.action.layout.desc': 'สร้างเมนูรูปแบบสวยงาม',
    'dash.action.social': 'ส่งออกโซเชียลมีเดีย',
    'dash.action.social.desc': 'Facebook, Instagram, LINE OA',
    'dash.action.poster': 'โปสเตอร์รีวิว',
    'dash.action.poster.desc': 'สร้างโปสเตอร์จากรีวิวลูกค้า',
    'dash.action.festival': 'แม่แบบเทศกาลไทย',
    'dash.action.festival.desc': 'สงกรานต์ ตรุษจีน ลอยกระทง',
    'dash.recentActivity': 'กิจกรรมล่าสุด',
    'dash.noActivity': 'ยังไม่มีกิจกรรม เริ่มสร้างเนื้อหาเลย!',
    'dash.create.title': 'สร้างเนื้อหา',
    'dash.create.desc': 'เลือกฟีเจอร์จากหน้าหลักเพื่อเริ่มสร้าง',
    'dash.create.back': 'กลับหน้าหลัก',
    'dash.history.title': 'ประวัติการใช้งาน',
    'dash.settings.title': 'ตั้งค่าบัญชี',
    'dash.settings.name': 'ชื่อร้าน',
    'dash.settings.restaurant': 'ชื่อร้านอาหาร',
    'dash.settings.email': 'อีเมล',
    'dash.settings.lang': 'ภาษา',
    'dash.settings.save': 'บันทึก',
    'dash.settings.plan': 'แผนปัจจุบัน',
    'dash.settings.free': 'ฟรีตลอดไป',
    'dash.toast.used': 'ใช้เครดิต',
    'dash.toast.remain': 'คงเหลือ:',
    'dash.create.heroTitle': 'ออกแบบคอนเทนต์ถัดไปของร้าน',
    'dash.create.heroDesc': 'เลือกเวิร์กโฟลว์ที่ต้องการ แล้วเข้าสู่ Studio หรือศูนย์จัดการที่เหมาะกับงานนั้นทันที',
    'dash.route.referral': 'แนะนำเพื่อน',
    'dash.home.heroTitle': 'ยกระดับภาพเมนูและการเติบโตของร้านในที่เดียว',
    'dash.home.heroDesc': 'เปิด Studio เพื่อสร้างภาพใหม่ จากนั้นไหลต่อไปยังคลังผลงาน ประวัติ และศูนย์โปรโมตโดยไม่หลุดจากพื้นที่ทำงานเดียวกัน',
    'dash.home.primaryCta': 'เข้า Studio',
    'dash.home.secondaryCta': 'เปิดคลังผลงาน',
    'dash.home.referralTitle': 'ศูนย์เติบโตและการแนะนำ',
    'dash.home.referralDesc': 'ติดตามลิงก์ชวนเพื่อน การแปลงผล ค่าคอมมิชชั่นที่รอดำเนินการ และยอดที่พร้อมแลกในมุมมองเดียว',
    'dash.home.activityViewAll': 'ดูทั้งหมด',
    'dash.home.studioTitle': 'Studio',
    'dash.home.libraryTitle': 'คลังผลงาน',
    'dash.home.libraryDesc': 'จัดการภาพต้นฉบับ ผลลัพธ์ที่สร้าง และงานที่เผยแพร่ในพื้นที่กว้างที่อ่านง่ายกว่าเดิม',
    'dash.home.settingsDesc': 'ดูแลข้อมูลร้าน ภาษา และแพ็กเกจบัญชี โดยไม่ต้องหลุดจากประสบการณ์ Dashboard',
    'dash.create.workflow.studioTitle': 'AI Studio',
    'dash.create.workflow.studioDesc': 'สร้าง ปรับแต่ง และเลือกภาพอาหารเวอร์ชันสมบูรณ์ในพื้นที่ทำงานเฉพาะทาง',
    'dash.create.workflow.libraryTitle': 'Asset Library',
    'dash.create.workflow.libraryDesc': 'รีวิวภาพที่อัปโหลด ผลลัพธ์ที่สร้าง และสินทรัพย์ที่เผยแพร่ในตัวจัดการที่กว้างและชัดเจนกว่าเดิม',
    'dash.create.workflow.historyTitle': 'History Center',
    'dash.create.workflow.historyDesc': 'เข้าไปดูบิล งานสร้างย้อนหลัง และบันทึกการใช้งานผ่านเส้นทางที่แชร์ลิงก์ได้จริง',
    'dash.create.stepLabel': 'ขั้นตอน',
    'dash.create.flowTitle': 'Production Flow',
    'dash.create.flowDesc': 'Dashboard ใหม่ควรเป็นตัวจัดเส้นทางและการจัดการ ส่วน Studio เป็นแกนกลางของงานสร้างจริง',
    'dash.create.adaptiveTitle': 'Adaptive Workspace',
    'dash.create.adaptiveDesc': 'หน้า Library, History และ Referral ไม่ควรถูกบีบอยู่ในคอนเทนเนอร์แคบแบบเดิมอีกต่อไป',
  },
  zh: {
    'dash.credits': '剩余积分',
    'dash.creditReset': '每月重置',
    'dash.nav.home': '主页',
    'dash.nav.create': '创建内容',
    'dash.nav.library': '资料库',
    'dash.nav.history': '历史',
    'dash.nav.settings': '设置',
    'dash.upgrade.title': '升级到 Pro',
    'dash.upgrade.desc': '解锁社交媒体导出和评价海报功能',
    'dash.upgrade.btn': '升级 ฿249/月',
    'dash.upgrade.btn2': '升级',
    'dash.logout': '退出登录',
    'dash.welcome.label': '欢迎回来',
    'dash.welcome.prefix': '你好,',
    'dash.creditsLeft': '积分剩余',
    'dash.creditOverview': '本月积分概览',
    'dash.cr': '积分',
    'dash.resetDate': '重置日期: 2026年5月1日',
    'dash.feat.copy': 'AI 文案',
    'dash.feat.enhance': '图片优化',
    'dash.feat.social': '社交媒体',
    'dash.feat.collage': '多图拼接',
    'dash.free': '免费',
    'dash.perUse': '积分/次',
    'dash.quickActions': '快速开始',
    'dash.action.generate': 'AI 生成图片',
    'dash.action.generate.desc': '上传并优化食物图片',
    'dash.action.copy': 'AI 写广告语',
    'dash.action.copy.desc': '自动生成菜单描述',
    'dash.action.layout': '菜单排版设计',
    'dash.action.layout.desc': '创建精美菜单版式',
    'dash.action.social': '社交媒体导出',
    'dash.action.social.desc': 'Facebook, Instagram, LINE OA',
    'dash.action.poster': '评价海报',
    'dash.action.poster.desc': '根据客户评价生成海报',
    'dash.action.festival': '泰国节日模板',
    'dash.action.festival.desc': '宋干节 春节 水灯节',
    'dash.recentActivity': '最近活动',
    'dash.noActivity': '还没有活动，开始创建内容吧！',
    'dash.create.title': '创建内容',
    'dash.create.desc': '从主页选择功能开始创建',
    'dash.create.back': '返回主页',
    'dash.history.title': '使用历史',
    'dash.settings.title': '账户设置',
    'dash.settings.name': '店铺名称',
    'dash.settings.restaurant': '餐厅名称',
    'dash.settings.email': '电子邮箱',
    'dash.settings.lang': '语言',
    'dash.settings.save': '保存',
    'dash.settings.plan': '当前套餐',
    'dash.settings.free': '永久免费',
    'dash.toast.used': '消耗积分',
    'dash.toast.remain': '剩余:',
    'dash.create.heroTitle': '为门店选择下一步创作流程',
    'dash.create.heroDesc': '按任务进入对应工作流，直接去 Studio 生成，或者进入资料与历史中心继续处理。',
    'dash.route.referral': '推广中心',
    'dash.home.heroTitle': '在一个工作台里完成菜单内容生成与增长运营',
    'dash.home.heroDesc': '先进入 Studio 生成内容，再无缝流转到资料库、历史中心和推广中心，不必在多个割裂页面来回跳转。',
    'dash.home.primaryCta': '进入 Studio',
    'dash.home.secondaryCta': '打开资料库',
    'dash.home.referralTitle': '增长与推广中心',
    'dash.home.referralDesc': '集中查看邀请链接、转化数据、待结算佣金和可兑换资产，让增长链路更清楚。',
    'dash.home.activityViewAll': '查看全部',
    'dash.home.studioTitle': 'Studio',
    'dash.home.libraryTitle': '资料库',
    'dash.home.libraryDesc': '管理原始素材、生成结果与已发布资产，在更宽的空间里完成筛选和处理。',
    'dash.home.settingsDesc': '在 Dashboard 内完成店铺资料、语言偏好与账号套餐的统一维护。',
    'dash.create.workflow.studioTitle': 'AI Studio',
    'dash.create.workflow.studioDesc': '在专属工作台中生成、精修并挑选最终的菜品图片结果。',
    'dash.create.workflow.libraryTitle': 'Asset Library',
    'dash.create.workflow.libraryDesc': '查看已上传素材、生成结果和发布资产，并在更自适应的管理空间中继续处理。',
    'dash.create.workflow.historyTitle': 'History Center',
    'dash.create.workflow.historyDesc': '通过可路由化的页面查看账单流、任务历史与操作审计，不再困在单页切换里。',
    'dash.create.stepLabel': '步骤',
    'dash.create.flowTitle': '生产流程',
    'dash.create.flowDesc': '新的 Dashboard 负责路由与管理，Studio 负责真正的内容生产，不再让所有功能挤在一个平面里。',
    'dash.create.adaptiveTitle': '自适应工作区',
    'dash.create.adaptiveDesc': 'Library、History、Referral 这类宽页面不应该再被旧版 Dashboard 的窄容器压瘪。',
  },
  en: {
    'dash.credits': 'Credits remaining',
    'dash.creditReset': 'Resets monthly',
    'dash.nav.home': 'Home',
    'dash.nav.create': 'Create',
    'dash.nav.library': 'Library',
    'dash.nav.history': 'History',
    'dash.nav.settings': 'Settings',
    'dash.upgrade.title': 'Upgrade to Pro',
    'dash.upgrade.desc': 'Unlock social media export and review posters',
    'dash.upgrade.btn': 'Upgrade ฿249/mo',
    'dash.upgrade.btn2': 'Upgrade',
    'dash.logout': 'Log out',
    'dash.welcome.label': 'Welcome back',
    'dash.welcome.prefix': 'Hello,',
    'dash.creditsLeft': 'credits remaining',
    'dash.creditOverview': "This month's credits",
    'dash.cr': 'cr',
    'dash.resetDate': 'Resets May 1, 2026',
    'dash.feat.copy': 'AI Copy',
    'dash.feat.enhance': 'Enhancement',
    'dash.feat.social': 'Social Export',
    'dash.feat.collage': 'Collage',
    'dash.free': 'Free',
    'dash.perUse': 'cr/use',
    'dash.quickActions': 'Quick Actions',
    'dash.action.generate': 'AI Image Generation',
    'dash.action.generate.desc': 'Upload and enhance food photos',
    'dash.action.copy': 'AI Copywriting',
    'dash.action.copy.desc': 'Auto-generate menu descriptions',
    'dash.action.layout': 'Menu Layout Design',
    'dash.action.layout.desc': 'Create beautiful menu layouts',
    'dash.action.social': 'Social Media Export',
    'dash.action.social.desc': 'Facebook, Instagram, LINE OA',
    'dash.action.poster': 'Review Poster',
    'dash.action.poster.desc': 'Generate posters from customer reviews',
    'dash.action.festival': 'Thai Festival Templates',
    'dash.action.festival.desc': 'Songkran, CNY, Loy Krathong',
    'dash.recentActivity': 'Recent Activity',
    'dash.noActivity': 'No activity yet — start creating content!',
    'dash.create.title': 'Create Content',
    'dash.create.desc': 'Choose a feature from home to start creating',
    'dash.create.back': 'Back to Home',
    'dash.history.title': 'Usage History',
    'dash.settings.title': 'Account Settings',
    'dash.settings.name': 'Store name',
    'dash.settings.restaurant': 'Restaurant name',
    'dash.settings.email': 'Email',
    'dash.settings.lang': 'Language',
    'dash.settings.save': 'Save',
    'dash.settings.plan': 'Current plan',
    'dash.settings.free': 'Free forever',
    'dash.toast.used': 'Credits used',
    'dash.toast.remain': 'Remaining:',
    'dash.create.heroTitle': 'Choose the next workflow for your store',
    'dash.create.heroDesc': 'Jump into Studio for image generation, or open the right management center for your next action.',
    'dash.route.referral': 'Referral Center',
    'dash.home.heroTitle': 'Run menu creation and growth from one workspace',
    'dash.home.heroDesc': 'Launch Studio for production, then move through Library, History, and Referral without dropping into disconnected views.',
    'dash.home.primaryCta': 'Open Studio',
    'dash.home.secondaryCta': 'Open Library',
    'dash.home.referralTitle': 'Growth & Referral Center',
    'dash.home.referralDesc': 'Track invite links, conversions, pending commissions, and redeemable assets inside one focused workspace.',
    'dash.home.activityViewAll': 'View All',
    'dash.home.studioTitle': 'Studio',
    'dash.home.libraryTitle': 'Library',
    'dash.home.libraryDesc': 'Manage source materials, generated assets, and published outputs with a wider adaptive workspace.',
    'dash.home.settingsDesc': 'Update business profile, language preferences, and account plan settings without leaving the dashboard flow.',
    'dash.create.workflow.studioTitle': 'AI Studio',
    'dash.create.workflow.studioDesc': 'Generate, refine, and select polished food images inside the dedicated Studio workspace.',
    'dash.create.workflow.libraryTitle': 'Asset Library',
    'dash.create.workflow.libraryDesc': 'Review uploaded photos, generated results, and shared assets in a wider adaptive manager.',
    'dash.create.workflow.historyTitle': 'History Center',
    'dash.create.workflow.historyDesc': 'Jump into billing flow, job history, and operation audit records with route-level deep links.',
    'dash.create.stepLabel': 'Step',
    'dash.create.flowTitle': 'Production Flow',
    'dash.create.flowDesc': 'Dashboard now handles routing and management, while Studio stays focused on the actual generation workflow.',
    'dash.create.adaptiveTitle': 'Adaptive Workspace',
    'dash.create.adaptiveDesc': 'Wide management pages like Library, History, and Referral should no longer be constrained by the old narrow dashboard shell.',
  },
};

export function getDashboardText(lang: string, key: string): string {
  const normalized = lang === 'th' || lang === 'zh' || lang === 'en' ? lang : 'en';
  return dashboardCopy[normalized][key] || dashboardCopy.en[key] || key;
}
