export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#060608] text-white py-16">
      <div className="max-w-3xl mx-auto px-6">
        <div className="mb-10">
          <p className="text-sm text-primary-400 font-semibold uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-3xl sm:text-4xl font-black mb-3 text-white">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: April 14, 2026</p>
        </div>

        <div className="glass rounded-3xl p-8 md:p-12 border-white/10 prose prose-invert max-w-none">
          <p className="text-gray-400 mb-6">
            These Terms of Service ("Terms") govern your use of the AI Menu Growth Engine website and services ("Services"). By accessing or using our Services, you agree to be bound by these Terms.
          </p>

          <h2 className="text-2xl font-bold text-white mt-10 mb-4 pb-2 border-b border-white/10">1. Acceptance of Terms</h2>
          <p className="text-gray-400 mb-6">
            By creating an account, uploading images, or generating content, you confirm that you have the legal authority to accept these Terms on behalf of yourself or the business entity you represent.
          </p>

          <h2 className="text-2xl font-bold text-white mt-10 mb-4 pb-2 border-b border-white/10">2. Use of Services and AI Credits</h2>
          <ul className="list-disc pl-6 text-gray-400 space-y-2 mb-6">
            <li><strong>AI Credits:</strong> Services (image enhancement, copy generation, multi-language translation) consume AI credits. Credits are purchased via subscription or pay-as-you-go.</li>
            <li><strong>Fair Use:</strong> You may not use our Services to generate illegal, hateful, or explicit content. Automated scraping or reverse-engineering of our AI endpoints is strictly prohibited.</li>
            <li><strong>Availability:</strong> We strive for 99.9% uptime but do not guarantee uninterrupted access. Service may be paused for maintenance.</li>
          </ul>

          <h2 className="text-2xl font-bold text-white mt-10 mb-4 pb-2 border-b border-white/10">3. Intellectual Property Rights</h2>
          <p className="text-gray-400 mb-4">When you use our Services:</p>
          <ul className="list-disc pl-6 text-gray-400 space-y-2 mb-6">
            <li><strong>Your Input:</strong> You retain all ownership rights to the original photos and menus you upload. You grant us a temporary license to process them solely to provide the Service to you.</li>
            <li><strong>AI Output:</strong> You are granted a full, commercial, royalty-free license to use the enhanced images, descriptions, and digital menus generated by our AI for your business operations.</li>
            <li><strong>Our Platform:</strong> We retain all rights to our software, algorithms, UI/UX, and branding.</li>
          </ul>

          <h2 className="text-2xl font-bold text-white mt-10 mb-4 pb-2 border-b border-white/10">4. Subscriptions, Payments, and Refunds</h2>
          <p className="text-gray-400 mb-6">
            Subscriptions are billed in advance on a monthly or annual basis. You may cancel your subscription at any time, but we do not provide refunds for unused credits or partial billing periods unless required by law.
          </p>

          <h2 className="text-2xl font-bold text-white mt-10 mb-4 pb-2 border-b border-white/10">5. Limitation of Liability</h2>
          <p className="text-gray-400 mb-6">
            Our Services are provided "AS IS". We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to loss of revenue, data, or business interruption.
          </p>

          <h2 className="text-2xl font-bold text-white mt-10 mb-4 pb-2 border-b border-white/10">6. Changes to Terms</h2>
          <p className="text-gray-400 mb-6">
            We reserve the right to modify these Terms at any time. We will notify you of material changes via email or an in-app notification. Continued use of the Services constitutes acceptance of the revised Terms.
          </p>
        </div>
      </div>
    </div>
  );
}
